### ISSUE TITLE
ongenerate hook deprecation since v1.0.0 

### ISSUE THREAD

**Issue by icek** [leogr/rollup-plugin-html-entry#2]
Since the release of version 1.0.0 some of the hooks are deprecated. See: https://github.com/rollup/rollup/releases/tag/v1.0.0
I am getting the following warning in the console:
```
(!) Plugin at position 4 plugin: The ongenerate hook used by plugin at position 4 is deprecated.
The generateBundle hook should be used instead.
```

**Comment by leogr** [comment]
Hi @icek 

Sorry for the very delayed reply.
I need some spare time to dig into that, and refactor it.
Have you found any solution meanwhile? If so feel free to file a PR or just give me any feedback that can help.

Thanks in advance
